version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
      other:
        patterns:
          - "*"
        exclude-patterns:
          - "Microsoft.*"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    groups:
      python-packages:
        patterns:
          - "*"
