version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      aspnet:
        patterns:
          - "Microsoft.AspNetCore*"
          - "Microsoft.Extensions.WebEncoders"
      entityframework:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      extensions:
        patterns:
          - "Microsoft.Extensions*"
        exclude_patterns:
          - "Microsoft.Extensions.WebEncoders" # this one follows ASP.NET versioning scheme
      identityserver:
        patterns:
          - "IdentityServer*"
      masstransit:
        patterns:
          - "MassTransit*"
      serilog:
        patterns:
          - "Serilog*"
      xunit:
        patterns:
          - "xunit*"
