site_name: LeanCode CoreLibrary
repo_url: https://github.com/leancodepl/corelibrary
docs_dir: ./docs
theme:
  logo: leancode_logo.png
  name: material
  features:
    - navigation.indexes
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Overview: ./README.md
  - CQRS:
    - ./cqrs/index.md
    - Pipeline:
      - ./cqrs/pipeline/index.md
      - Adding custom middlewares: ./cqrs/pipeline/adding_custom_middlewares.md
      - Avoid committing transactions in handlers: ./cqrs/pipeline/avoid_commiting_transactions_in_handlers.md
    - Command:
      - ./cqrs/command/index.md
    - Query:
      - ./cqrs/query/index.md
    - Operation:
      - ./cqrs/operation/index.md
    - Authorization:
      - ./cqrs/authorization/index.md
    - Validation:
      - ./cqrs/validation/index.md
  - Domain:
    - ./domain/index.md
    - Aggregate:
      - ./domain/aggregate/index.md
    - Identifiable:
      - ./domain/identifiable/index.md
    - Value object:
      - ./domain/value_object/index.md
    - Domain event:
      - ./domain/domain_event/index.md
    - Id:
      - ./domain/id/index.md
    - Time provider:
      - ./domain/time_provider/index.md
  - External integrations:
    - Authorization - Ory Kratos:
      - ./external_integrations/authorization_ory_kratos/index.md
      - Handling webhooks: ./external_integrations/authorization_ory_kratos/handling_webhooks.md
    - Emails - SendGrid:
      - ./external_integrations/emails_sendgrid/index.md
    - Feature flags - ConfigCat:
      - ./external_integrations/feature_flags_configcat/index.md
    - Logging - Serilog:
      - ./external_integrations/logging_serilog/index.md
      - Sanitization: ./external_integrations/logging_serilog/sanitization.md
    - Messaging - MassTransit:
      - ./external_integrations/messaging_masstransit/index.md
      - Handling events: ./external_integrations/messaging_masstransit/handling_events.md
    - Push notifications - FCM:
      - ./external_integrations/push_notifications_fcm/index.md
  - Features:
    - Audit logs:
      - ./features/audit_logs/index.md
    - Force update:
      - ./features/force_update/index.md
    - Localization:
      - ./features/localization/index.md
  - Tests:
    - Faking time:
      - ./tests/faking_time/index.md
    - Integration tests:
      - ./tests/integration_tests/index.md
  - CoreLibrary 8.0 changes overview & migration guide:
    - ./v8_migration_guide/index.md
