site_name: LeanCode CoreLibrary
repo_url: https://github.com/leancodepl/corelibrary
docs_dir: ./docs
theme:
  name: material
  features:
    - navigation.indexes
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
