site_name: LeanCode CoreLibrary
repo_url: https://github.com/leancodepl/corelibrary
docs_dir: ./docs
theme:
  name: material
  features:
    - navigation.indexes
markdown_extensions:
  - admonition
  - footnotes
nav:
  - Overview: README.md
  - General:
    - ./general/README.md
    - ./general/building_and_testing.md
    - ./general/project_structure.md
    - ./general/versioning_and_support_matrix.md
  - Basics:
    - ./basics/README.md
    - ./basics/app.md
    - ./basics/cqrs.md
    - ./basics/mass_transit_integration.md
  - Domain Concepts:
    - ./domain/README.md
    - ./domain/ids.md
    - ./domain/aggregates.md
  - Guides:
    - Overview: ./guides/README.md
    - Basics:
      - ./guides/basic/creating_an_aggregate.md
      - ./guides/basic/writing_commands.md
      - ./guides/basic/writing_queries.md
      - ./guides/basic/authorization.md
      - ./guides/basic/handling_events.md
      - ./guides/basic/pipeline.md
    - Features:
      - ./guides/features/force_update.md
    - Advanced:
      - ./guides/advanced/v8_migration_guide.md
  - ADRs:
    - Overview: ./adrs/README.md
    - Value Objects: ./adrs/2021-02-04_value_object.md
    - Optimistic Concurrency: ./adrs/2021-11-25_optimistic_concurrency.md
