name: CoreLibrary Docs

on:
  push:
    paths:
    - 'docs/**'
  pull_request:
    paths:
    - 'docs/**'

jobs:
  lint-changelog:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint docs
      uses: DavidAnson/markdownlint-cli2-action@v13
      with:
        config: ./docs/.markdownlint.jsonc
        globs: 'docs/**/*.md'
